name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login GHCR
      run: docker login --username atmega1337 --password ${{ secrets.API_GHCR }} ghcr.io
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag djeban_discordbot:latest
    - name: Docker push
      run: docker push ghcr.io/atmega1337/djeban_discordbot:latest
